# Generated by Django 4.2.5 on 2024-02-03 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_remove_filmwork_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmwork',
            name='file_path',
        ),
    ]
